/**
 * Common Javascript
 *
 * @author
 * Date 6/9/2018
 */

var commonMsg = {
	JSE001: "Please fill %s!",
	JSE002: "Please choose %s!",
	JSE003: "Please choose %s only!",
	JSE004: "Please check %s !",
	JSE005: "Upload File name is already exists. Do you want to replace?",
	JSE006: "Please fill %s in English Character Only!",
	JSE007: "Please fill %s in Number Only!",
	JSE008:
		"You do not check all records.Are you sure want to save the checked records?",
	JSE009: "Are you sure want to save all the records?",
	JSE010:
		"Password must contain Capital & Small Letters & Special Characters & Numbers!",
	JSE011: "Please fill %s at least 12 characters or numbers!",
	JSE012: "Are you sure want to Cancellation?",
	JSE013: "Please fill %s only 2 decimal number!",
	JSE014:
		"%s only allow 10 digit for positive number and 9 digit for negative number and 2 decimal place.",
	JSE015: "Please fill data in each row!",
	JSE016: "Password and Confirm Password do not match!",
	JSE017: "Are you sure you want to delete?",
	JSE018: "Please fill Data!",
	JSE019: "%s is not allow special character!",
	JSE020: "Are you sure want to update?",
	JSE021: "Data cannot be saved!",
	JSE022: "Are you sure you want to approve all records?",
	JSE023: "Please fill Retention Reason in each checked rows!",
	JSE024: "Please choose a file to upload!",
	JSE025: "Please choose Report Necessity or Completion flag!",
	JSE026: "To Date is greater than or equal to From Date!",
	JSE027: "Something wrong! Please refresh the page.",
	JSE028: "There is no data to save!",
	JSE029: "Please fill Comment in each checked rows!",
	JSE030: "Please fill Comment in each unchecked rows!",
	JSE031: "Upload file size shouldn't be larger than 10MB!",
	JSE032: "Please fill reason in each Label uncheck row!",
	JSE033: "Upload failed:there are duplicate files. Please upload again!",
	JSE034: "Please select row to request!",
	JSE035: "Can't upload over 100 pictures. Please upload again!",
	JSE036: "Upload file name shouldn't be larger than 10 characters!",
	JSE037: "File extension is not allowed: %s",
	JSE038: "User is not allowed to access this BA.",
	JSE039: "Please fill comment in each Physical uncheck row!",
	JSE040:
		"Please fill comment in each Physical uncheck row and reason in each Label uncheck row!",
	JSE041: "[From] Value should be less than or equal to [To] Value!",
	JSE042: "The number of records to be downloaded must not exceed 160 records!",
	JSE043: "Are you sure you want to reject?",
	JSE044: "Date format is not allowed: %s",
	JSE045: "Please fill the net income (forecast) %s!",
	JSE046:
		"Please choose year between start of budget year and end of budget year!",
	JSE047: "%s is allow only 12 digits with 2 decimal place!",
	JSE048: "%s is allow only 6 digits with 2 decimal place!",
	JSE049: "Please fill only 12 digits with 2 decimal place!",
	JSE050: "Please fill Logistic Index No. in table %s!",
	JSE051:
		"Please fill destination(Internal Payment History) in Logistic Index No. %s!",
	JSE052: "Transaction Total is not equal to actual result amount!",
	JSE053: "Maximum limit of rows are %s rows!",
	JSE054: "%s is already chosen. Please choose another one!",
	JSE055: "Logistic Index No.(%s) are duplicated!",
	JSE056: "Please fill only 9 digits with 2 decimal place!",
	JSE057: "%s allows only 5 characters",
	JSE058: "Trading name (%s) used in Trading plan form",
	JSE059: "This data is already used in Trading Plan",
	JSE060: "The data to be copied must not be the same",
	JSE061: "Please fill only 10 digits with 3 decimal place!",
	JSE062: "Maximum limit of tables are %s tables!",
	JSE063: "%s is not allow spaces!",
	JSE064: "Please fill %s Characters only!",
	JSE065: "Please fill reason if applicable is checked!",
	JSE066: "Please fill comment if check is checked!",
	JSE067: "%s %s is referenced by %s %s!",
	JSE068: "%s %s is already inactive.",
	JSE069: "Please select different Item name, Headquarter and Department.",
	JSE070: "Some headquarters have been already queued to backup!",
	JSE071: "Please choose that start month must be less than end month!",
	JSE072: "Skip already Saved datas?",
	JSE073: "Want to save skip already Approved datas?",
	JSE074: "Please fill 社内受払手数料 of text box!",
	JSE075:
		"社内受払手数料 of text and destination(Internal Payment History) are duplicated in table %s!",
	JSE076: "Please fill 社内受払手数料 of text box in table %s!",
	JSE077: "Unit Price of %s changes from %s to %s!",
	JSE078: "Do you want to update the changed unit price?",
	JSE079: "%s is experied.Please update %s!",
	JSE080: "You don't have permission!",
	JSE081: "Please fill %s in Number & English Character Only!",
	JSE082: "There is no related business area for this event!",
	JSE083: "Password did not match!",
	JSE084: "Please fill only 9 digits with 5 decimal place!",
	JSE085: "%s must be number only.",
	JSE086: "Plesase select the account type.",
	JSE087: "%s can not be more than %s characters and numbers!",
	JSE088: "Resigned Date must be greater than Joined Date.",
	JSE089: "Please choose Page Name before Process.",
	JSE090: "Read Action should be %s or higher.",
	JSE091: "Read Action should be %s.",
	JSE092: "From Date and To Date must be between %s From Date and To Date.",
	JSE093: "%s is greater than one.",
	JSE094: "Maximum number of characters can't be over 500.",
	JSE095: "Please fill comment!",
	JSE096: "User Name is already inputted. Please input another one!",
	JSE097: "Budget Person Total（①+②）must not be a negative value.",
	JSE098: "Budget Person Total can't be greater than Number Of Personnel Total.",
	JSE099: "Please choose Position Name for New User!",
	JSE100: "The total exceeds 100%s.",

};
